### ISSUE TITLE
Scenic causes `ar_internal_metadata` table to be dumped to schema.rb

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/scenic#194]
I added scenic to my first project with Rails 5 today and noticed this appeared in the schema dump:

```diff
+  create_table "ar_internal_metadata", primary_key: "key", id: :string, force: :cascade do |t|
+    t.string   "value"
+    t.datetime "created_at", null: false
+    t.datetime "updated_at", null: false
+  end
+
```

The project has been running for 6+ months without this table appearing in the schema, so it seems likely caused by Scenic. It seems harmless, but probably not something we should be dumping.

**Comment by teoljungberg** [comment]
I did a quick search, and couldn't reproduce the issue. My initial impression was that the schema dumber wasn't properly ignoring the table, but no dice.

The diff I tried to reproduce the issue is:

```diff
diff --git a/lib/scenic/schema_dumper.rb b/lib/scenic/schema_dumper.rb
index c42f6a9..6e3e388 100644
--- a/lib/scenic/schema_dumper.rb
+++ b/lib/scenic/schema_dumper.rb
@@ -30,7 +30,11 @@ module Scenic
     unless ActiveRecord::SchemaDumper.instance_methods(false).include?(:ignored?)
       # This method will be present in Rails 4.2.0 and can be removed then.
       def ignored?(table_name)
-        ["schema_migrations", ignore_tables].flatten.any? do |ignored|
+        [
+          "ar_internal_metadata",
+          "schema_migrations",
+          ignore_tables,
+        ].flatten.any? do |ignored|
           case ignored
           when String; remove_prefix_and_suffix(table_name) == ignored
           when Regexp; remove_prefix_and_suffix(table_name) =~ ignored
diff --git a/spec/scenic/schema_dumper_spec.rb b/spec/scenic/schema_dumper_spec.rb
index f3e33ec..5048786 100644
--- a/spec/scenic/schema_dumper_spec.rb
+++ b/spec/scenic/schema_dumper_spec.rb
@@ -36,4 +36,18 @@ describe Scenic::SchemaDumper, :db do
       Search.connection.drop_view :'scenic.searches'
     end
   end
+
+  it "ignores tables internal to Rails" do
+    view_definition = "SELECT 'needle'::text AS haystack"
+    Search.connection.create_view :searches, sql_definition: view_definition
+    stream = StringIO.new
+
+    ActiveRecord::SchemaDumper.dump(Search.connection, stream)
+
+    output = stream.string
+
+    expect(output).to include "create_view :searches"
+    expect(output).not_to include "ar_internal_metadata"
+    expect(output).not_to include "schema_migrations"
+  end
 end
```

**Comment by andimrob** [comment]
I am also experiencing this issue. Definitely an issue with Scenic. When I removed Scenic from my Gemfile the issue stops immediately.

**Comment by calebthompson** [comment]
https://github.com/rails/rails/blob/2840c429cc1cf0edb6e6549f7581b782021a71f9/activerecord/lib/active_record/schema_dumper.rb#L239-L243 ignores that table, so the problem is that we're not loading that method properly, not that we haven't special cased ar_internal_metadata. That table was introduced in 5.0 and the ignored? method in 4.2. We may be defining the method ourselves instead of loading Rails' version.

**Comment by teoljungberg** [comment]
@calebthompson You're correct there, the method was probably included and overridden because we support Rails 4.0 and 4.1 (which does not have `ignored?` defined.

But, we shouldn't be using if if `ignored?` is defined as per https://github.com/teoljungberg/scenic/blob/940b0c39f9e6799a2a9eddfebdfe82e575634008/lib/scenic/schema_dumper.rb#L30. So then why is this happening?

**Comment by calebthompson** [comment]
That method detection is probably wrong. The method is private, which may be the cause.

**Comment by calebthompson** [comment]
@sgrif You're a :thumbsdown: on making `ActiveRecord::SchemaDumper#ignored?` public?

**Comment by calebthompson** [comment]
Resolved in #198

**Comment by calebtocco** [comment]
I'm still experiencing this issue:
Rails 5.2.1
Scenic 1.5.1

Adding the below fixes the issue, as mentioned above:
ActiveRecord::SchemaDumper.ignore_tables += [
  'ar_internal_metadata'
]
